▶ Array View & Copy

In [1]:
import numpy as np

In [2]:
A = np.array([10, 20, 30])
B = A

In [3]:
B[0] = 99
A, B

(array([99, 20, 30]), array([99, 20, 30]))

In [4]:
B is A

True

In [5]:
id(A), id(B)

(1764849550512, 1764849550512)

In [6]:
# array B 를 따로 만들어준 것이 아니라 A 와 같은 곳에 할당되게 한 것

In [7]:
# shallow copy : 얕은 복사
# view()
A = np.array([10, 20, 30, 40])
B = A.view()

In [8]:
B is A

False

In [9]:
id(A), id(B)

(1765126302832, 1765126302352)

In [10]:
# view() 를 사용하면 id 가 다르게 부여되어 이번엔 A와 B가 다르게 된다.
B[0] = 99
A, B

(array([99, 20, 30, 40]), array([99, 20, 30, 40]))

In [11]:
# 현재 1차원에서는 앞서 B = A 와 같이 업데이트된 결과로 보이지만 shape 을 다르게 해주면 다름을 알 수 있다.
B.shape = (2, 2)
B[0][1] = 7
A, B

(array([99,  7, 30, 40]),
 array([[99,  7],
        [30, 40]]))

In [12]:
# deep copy
A = np.array([10, 20, 30, 40])
B = A.copy()

In [13]:
B is A

False

In [14]:
B[0] = 99
A, B

(array([10, 20, 30, 40]), array([99, 20, 30, 40]))

In [15]:
B.base is A

False

▶ 논리 연산 (Logical Operations)

In [16]:
import numpy as np

In [17]:
a = np.array([0, 1, 2])

In [18]:
# all() : 모든 값이 true 인가 ?
a.all()

False

In [19]:
# any() : 하나라도 true 인가 ? 
a.any()

True

In [20]:
# nonzero() : zero 가 아닌 값을 알려준다.
a.nonzero()

(array([1, 2], dtype=int64),)

In [21]:
# where() : 해당 조건에 맞는 값이 있는 index 를 반환
a = np.array([0, 1, 2])
np.where(a > 0)

(array([1, 2], dtype=int64),)

In [22]:
a= np.array([0, 10, 20])
np.where(a > 0)

(array([1, 2], dtype=int64),)

In [23]:
# 해당 값을 반환하는게 아니라 index 를 반환하는 것임을 보여주는 위 예시

In [24]:
np.where(a < 0)

(array([], dtype=int64),)

▶ Array Indexing & Slicing

In [25]:
# list indexing / Slicing 원리와 같다.

In [26]:
# 1차원
M1 = np.array([100., 101., 102., 103., 104.])

In [27]:
M1[0], M1[-1]

(100.0, 104.0)

In [28]:
M1[[0, 2]], M1[0:3:1]

(array([100., 102.]), array([100., 101., 102.]))

In [29]:
M1[:]

array([100., 101., 102., 103., 104.])

In [30]:
M1[::2]

array([100., 102., 104.])

In [31]:
M1[::-1]

array([104., 103., 102., 101., 100.])

In [32]:
# 2차원
M2 = np.array([[100., 101., 102.],
               [200., 201., 202.]])

In [33]:
M2[0]

array([100., 101., 102.])

In [34]:
M2[0][0], M2[0, 0]

(100.0, 100.0)

In [35]:
M2[1][2], M2[1, 2]

(202.0, 202.0)

In [36]:
M2[0, :]

array([100., 101., 102.])

In [37]:
M2[:, 0]

array([100., 200.])

In [38]:
M2[:, ::-1]

array([[102., 101., 100.],
       [202., 201., 200.]])

In [39]:
# 3차원
M3 = np.array(
    [
        [[100., 101., 102., 103.],
         [104., 105., 106., 107.],
         [108., 109., 110., 111.]],
        [[200., 201., 202., 203.],
         [204., 205., 206., 207.],
         [208., 209., 210., 211.]]
    ])

In [40]:
M3[0,:,:]

array([[100., 101., 102., 103.],
       [104., 105., 106., 107.],
       [108., 109., 110., 111.]])

In [41]:
# where() 를 활용
x = np.array([10., 20., 30.])
idx = np.where(x==30)
x[idx]

array([30.])

In [42]:
idx = (x==30)
x[idx]

array([30.])

In [43]:
# nonzero() 를 활용
x[np.where(x==30)]

array([30.])

In [44]:
x[np.nonzero(x==30)] # x==30 인 곳은 참이라 nonzero 일테니 해당 값이 반환된다.

array([30.])

In [45]:
# image processing
# image 검은색으로 만들기
IMAGE = np.array([[255, 0, 255],
                  [255, 0, 255],
                  [255, 0, 255]])
idx = np.where(IMAGE==255)
IMAGE[idx] = 0
IMAGE

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

▶ 선형대수 계산

In [46]:
M = np.array([[10, 20],
              [30, 40]])
N = np.array([[1, 2],
              [3, 4]])

In [47]:
# * : 같은 자리의 원소끼리 곱셈
M * N

array([[ 10,  40],
       [ 90, 160]])

In [48]:
# @ : 행렬의 곱셈 연산
M @ N

array([[ 70, 100],
       [150, 220]])

In [49]:
# dot() : 행렬의 곱셈 연산
M.dot(N)

array([[ 70, 100],
       [150, 220]])

In [50]:
# trace() : 대각선 방향의 원소들의 합을 반환
a = np.zeros((3, 3))
b = np.ones((3, 3))
np.trace(b)

3.0

In [51]:
# linalg.inv() : 역행렬 구하기
# M@x = y
M = np.array([[1., -3.],
              [2., 4.]])
y = np.array([[1.], [3.]])
M_inv = np.linalg.inv(M)
x = M_inv@y
M@x

array([[1.],
       [3.]])

In [52]:
M@M_inv # 항등행렬

array([[ 1.00000000e+00, -2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

In [53]:
# linalg.solve() : 행렬 문제 해결 / (a, b) 를 넣으면 ax = b 의 행렬 문제 계산에서 x 를 구해준다.
x = np.linalg.solve(M, y)

In [54]:
x

array([[1.3],
       [0.1]])

In [55]:
# eig() : 고유값 행렬
np.linalg.eig(M)

EigResult(eigenvalues=array([2.5+1.93649167j, 2.5-1.93649167j]), eigenvectors=array([[ 0.77459667+0.j ,  0.77459667-0.j ],
       [-0.38729833-0.5j, -0.38729833+0.5j]]))

In [56]:
# svd() : 특이값 분해 / singular value decomposition
np.linalg.svd(M)

SVDResult(U=array([[-0.52573111,  0.85065081],
       [ 0.85065081,  0.52573111]]), S=array([5.11667274, 1.95439508]), Vh=array([[ 0.22975292,  0.97324899],
       [ 0.97324899, -0.22975292]]))

In [57]:
# fill_diagonal() : 주대각행렬을 특정값으로 채우기
N = np.zeros((5, 5))
np.fill_diagonal(N, 100)
N

array([[100.,   0.,   0.,   0.,   0.],
       [  0., 100.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0., 100.,   0.],
       [  0.,   0.,   0.,   0., 100.]])

▶ Numpy 활용 예시

In [58]:
# A 의 첫줄 x 1, 둘째줄 x 2, 셋째줄 x 3 을 하려고 한다.
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
B = np.array([[1], [2], [3]])
B = B.repeat(3, axis=1)
B

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [59]:
C = A * B
C

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

In [60]:
# broadcasting
A = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
B = np.array([[1], [2], [3]])

In [61]:
A.shape, B.shape

((3, 3), (3, 1))

In [62]:
A * B # A, B 가 shape 이 맞지 않아도 알아서 맞춰서 계산해준다. repeat 에서 갱신할 필요가 없다.

array([[ 10,  20,  30],
       [ 80, 100, 120],
       [210, 240, 270]])

In [63]:
# function usage example
def f(x, y):
    return x*y
np.fromfunction(f, (5, 4), dtype=int)

array([[ 0,  0,  0,  0],
       [ 0,  1,  2,  3],
       [ 0,  2,  4,  6],
       [ 0,  3,  6,  9],
       [ 0,  4,  8, 12]])

In [64]:
# set
a = np.array([10, 20, 30, 40, 50])
b = np.array([30, 50])
np.setdiff1d(a, b) # 차집합 구하기

array([10, 20, 40])

In [65]:
# random.randint() : 해당 숫자까지 중에서 무작위 숫자 반환
x = np.random.randint(100)
x

7

In [66]:
# random.rand(n) : 0 부터 1까지 중에 무작위 n개의 숫자 반환
x = np.random.rand(5) 
x

array([0.59990784, 0.31851888, 0.38607086, 0.3180657 , 0.45537427])